#!/usr/bin/python
import argparse
import os
from xgoogle.search import GoogleSearch, SearchError


parser = argparse.ArgumentParser(description='gsearch: a tool for searching google')
parser.add_argument('-s','--search', help='Search String', required=True)
args = parser.parse_args()



def searchmain(searchstring):
  try:
    gs = GoogleSearch(searchstring)
    gs.results_per_page = 500
    print gs.results_per_page
    results = gs.get_results()
    for res in results:
      print res.title.encode("utf8")
      print res.desc.encode("utf8")
      print res.url.encode("utf8")
      print
  except SearchError, e:
    print "Search failed: %s" % e


def doMain():
  searchmain(args.search)



if __name__ == "__main__":
    doMain()
